# NASA Exoplanet Archive - Data Cleaning Pipeline
This Jupyter Notebook contains a robust Python data-cleaning pipeline developed for the Python + Power BI Data Visualization course.

The notebook performs setup, trimming, missing value analysis, two-stage imputation, and column renaming to output a pristine CSV (`cleaned_exoplanets.csv`) optimized for a dark-themed Power BI dashboard and aligned perfectly with lab report template requirements.

## 1. INITIAL SETUP & COLUMN TRIMMING
Load the exoplanet dataset, handle NASA's metadata comment lines starting with `#`, and filter immediately to the 29 core visualization columns.

In [1]:
# ==========================================

# 1. INITIAL SETUP & COLUMN TRIMMING

# ==========================================

import os

import pandas as pd

import numpy as np



# Load the exoplanet dataset, skipping NASA's comment lines starting with '#'

df = pd.read_csv('nasa_exoplanets.csv', comment='#')



# Filter to retain only the 29 core visualization columns

core_columns = [

    'pl_name', 'hostname', 'sy_snum', 'sy_pnum', 'sy_mnum', 'discoverymethod', 

    'disc_year', 'disc_facility', 'pl_orbper', 'pl_orbsmax', 'pl_rade', 'pl_radj', 

    'pl_bmasse', 'pl_bmassj', 'pl_bmassprov', 'pl_orbeccen', 'pl_insol', 'pl_eqt', 

    'st_spectype', 'st_teff', 'st_rad', 'st_mass', 'st_met', 'st_metratio', 

    'st_logg', 'ra', 'dec', 'sy_dist', 'sy_gaiamag'

]

df = df[core_columns]

print("Raw dataset loaded and filtered successfully.")

Raw dataset loaded and filtered successfully.

## 2. REPORT SECTION 2.2: INITIAL OVERVIEW
Execute shape analysis, print the row/column count cleanly, view data types/non-null counts using `df.info()`, and inspect the first few rows with `df.head()`.

In [2]:
# ==========================================

# Cell A: Run and display df.shape

# ==========================================

shape = df.shape

print(f"Number of Rows: {shape[0]}")

print(f"Number of Columns: {shape[1]}")

shape

Number of Rows: 6291
Number of Columns: 29

(6291, 29)

In [3]:
# ==========================================

# Cell B: Run and display df.info()

# ==========================================

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6291 entries, 0 to 6290
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pl_name          6291 non-null   object
 1   hostname         6291 non-null   object
 2   sy_snum          6291 non-null   int64
 3   sy_pnum          6291 non-null   int64
 4   sy_mnum          6291 non-null   int64
 5   discoverymethod  6291 non-null   object
 6   disc_year        6290 non-null   float64
 7   disc_facility    6291 non-null   object
 8   pl_orbper        5951 non-null   float64
 9   pl_orbsmax       5866 non-null   float64
 10  pl_rade          6241 non-null   float64
 11  pl_radj          6241 non-null   float64
 12  pl_bmasse        6260 non-null   float64
 13  pl_bmassj        6260 non-null   float64
 14  pl_bmassprov     6291 non-null   object
 15  pl_orbeccen      5241 non-null   float64
 16  pl_insol         4410 non-null   float64
 17  pl_eqt           4690 non-null   float64
 18  st_spectype      2324 non-null   object
 19  st_teff          5997 non-null   float64
 20  st_rad           5973 non-null   float64
 21  st_mass          6282 non-null   float64
 22  st_met           5652 non-null   float64
 23  st_metratio      5635 non-null   object
 24  st_logg          5969 non-null   float64
 25  ra               6291 non-null   float64
 26  dec              6291 non-null   float64
 27  sy_dist          6264 non-null   float64
 28  sy_gaiamag       5948 non-null   float64
dtypes: float64(19), int64(3), object(7)
memory usage: 1.4+ MB

In [4]:
# ==========================================

# Cell C: Run and display df.head()

# ==========================================

df.head()

      pl_name  hostname  sy_snum  ...        dec   sy_dist sy_gaiamag
0    11 Com b    11 Com        2  ...  17.793252   93.1846    4.44038
1    11 UMi b    11 UMi        1  ...  71.823943  125.3210    4.56216
2    14 And b    14 And        1  ...  39.235837   75.4392    4.91781
3    14 Her b    14 Her        1  ...  43.816362   17.9323    6.38300
4  16 Cyg B b  16 Cyg B        3  ...  50.516824   21.1397    6.06428

[5 rows x 29 columns]

## 3. REPORT SECTION 2.3: MISSING VALUE ANALYSIS
Generate a clean, copy-pasteable Markdown table matching your lab report layout that details null counts, missing percentage, and planned action strategy.

In [5]:
# ==========================================

# 3. REPORT SECTION 2.3: MISSING VALUE ANALYSIS

# ==========================================

# Execute isnull().sum() to display null counts

null_counts = df.isnull().sum()

print("Missing values per raw column:")

print(null_counts[null_counts > 0])



print("\n" + "="*80)

print("REPORT SECTION 2.3: MISSING VALUE ANALYSIS MARKDOWN TABLE")

print("="*80)



# Generate a clean, text-based Markdown table matching the report layout

# Columns: | Column Name | Missing Count | % Missing | Action Taken |

print("| Column Name | Missing Count | % Missing | Action Taken |")

print("|---|---|---|---|")

total_rows = len(df)

for col in df.columns:

    missing_count = null_counts[col]

    if missing_count > 0:

        pct_missing = (missing_count / total_rows) * 100

        # Determine imputation strategy / Action Taken

        if df[col].dtype == 'object':

            action = "Filled with 'Unknown' for categorical text"

        else:

            action = "Imputed via group median based on discovery method; global fallback if needed"

        print(f"| {col} | {missing_count} | {pct_missing:.2f}% | {action} |")

Missing values per raw column:
disc_year         1
pl_orbper       340
pl_orbsmax      425
pl_rade          50
pl_radj          50
pl_bmasse        31
pl_bmassj        31
pl_orbeccen    1050
pl_insol       1881
pl_eqt         1601
st_spectype    3967
st_teff         294
st_rad          318
st_mass           9
st_met          639
st_metratio     656
st_logg         322
sy_dist          27
sy_gaiamag      343
dtype: int64

================================================================================
REPORT SECTION 2.3: MISSING VALUE ANALYSIS MARKDOWN TABLE
================================================================================
| Column Name | Missing Count | % Missing | Action Taken |
|---|---|---|---|
| disc_year | 1 | 0.02% | Imputed via group median based on discovery method; global fallback if needed |
| pl_orbper | 340 | 5.40% | Imputed via group median based on discovery method; global fallback if needed |
| pl_orbsmax | 425 | 6.76% | Imputed via group median based on discovery method; global fallback if needed |
| pl_rade | 50 | 0.79% | Imputed via group median based on discovery method; global fallback if needed |
| pl_radj | 50 | 0.79% | Imputed via group median based on discovery method; global fallback if needed |
| pl_bmasse | 31 | 0.49% | Imputed via group median based on discovery method; global fallback if needed |
| pl_bmassj | 31 | 0.49% | Imputed via group median based on discovery method; global fallback if needed |
| pl_orbeccen | 1050 | 16.69% | Imputed via group median based on discovery method; global fallback if needed |
| pl_insol | 1881 | 29.90% | Imputed via group median based on discovery method; global fallback if needed |
| pl_eqt | 1601 | 25.45% | Imputed via group median based on discovery method; global fallback if needed |
| st_spectype | 3967 | 63.06% | Filled with 'Unknown' for categorical text |
| st_teff | 294 | 4.67% | Imputed via group median based on discovery method; global fallback if needed |
| st_rad | 318 | 5.05% | Imputed via group median based on discovery method; global fallback if needed |
| st_mass | 9 | 0.14% | Imputed via group median based on discovery method; global fallback if needed |
| st_met | 639 | 10.16% | Imputed via group median based on discovery method; global fallback if needed |
| st_metratio | 656 | 10.43% | Filled with 'Unknown' for categorical text |
| st_logg | 322 | 5.12% | Imputed via group median based on discovery method; global fallback if needed |
| sy_dist | 27 | 0.43% | Imputed via group median based on discovery method; global fallback if needed |
| sy_gaiamag | 343 | 5.45% | Imputed via group median based on discovery method; global fallback if needed |

## 4. REPORT SECTION 2.4: CLEANING ACTIONS & COLUMN RENAMING
Perform sequential cleaning actions: remove duplicates, apply two-stage imputation for numeric values, fill categorical nulls with "Unknown", force-cast `disc_year` to `int`, and rename all 29 columns. Outputs a copy-pasteable Markdown summary matching the Report Section 2.4 grid.

In [6]:
# ==========================================

# 4. REPORT SECTION 2.4: CLEANING ACTIONS & COLUMN RENAMING

# ==========================================

# a) Remove duplicate rows

initial_rows = len(df)

df.drop_duplicates(inplace=True)

duplicates_removed = initial_rows - len(df)



# Identify numeric and categorical columns

numeric_cols = df.select_dtypes(include=['number']).columns.tolist()

categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()



# b) Handle missing values with a robust two-stage strategy

# 1. Fill numeric with group median based on 'discoverymethod'

for col in numeric_cols:

    group_medians = df.groupby('discoverymethod')[col].transform('median')

    df[col] = df[col].fillna(group_medians)

    

    # 2. Fill remaining numeric nulls with global median fallback

    global_median = df[col].median()

    if not pd.isna(global_median):

        df[col] = df[col].fillna(global_median)

    else:

        df[col] = df[col].fillna(0)



# 3. Fill categorical cells with "Unknown"

for col in categorical_cols:

    df[col] = df[col].fillna("Unknown")



# c) Force-cast disc_year to an integer type (int)

df['disc_year'] = df['disc_year'].astype(int)



# d) Convert Distance from Parsecs to Light Years (1 Parsec = 3.26156 Light Years)

df['sy_dist'] = df['sy_dist'] * 3.26156



# e) RENAME ALL 29 COLUMNS

rename_dict = {

    'pl_name': 'Planet_Name',

    'hostname': 'Host_Star_Name',

    'sy_snum': 'Number_of_Stars',

    'sy_pnum': 'Number_of_Planets',

    'sy_mnum': 'Number_of_Moons',

    'discoverymethod': 'Discovery_Method',

    'disc_year': 'Discovery_Year',

    'disc_facility': 'Discovery_Facility',

    'pl_orbper': 'Orbital_Period_Days',

    'pl_orbsmax': 'Orbital_Distance_AU',

    'pl_rade': 'Planet_Radius_Earth_Units',

    'pl_radj': 'Planet_Radius_Jupiter_Units',

    'pl_bmasse': 'Planet_Mass_Earth_Units',

    'pl_bmassj': 'Planet_Mass_Jupiter_Units',

    'pl_bmassprov': 'Mass_Measurement_Type',

    'pl_orbeccen': 'Orbit_Eccentricity',

    'pl_insol': 'Insolation_Flux_Earth_Units',

    'pl_eqt': 'Equilibrium_Temperature_K',

    'st_spectype': 'Star_Spectral_Type',

    'st_teff': 'Star_Temperature_K',

    'st_rad': 'Star_Radius_Solar_Units',

    'st_mass': 'Star_Mass_Solar_Units',

    'st_met': 'Star_Metallicity',

    'st_metratio': 'Star_Metallicity_Ratio',

    'st_logg': 'Star_Surface_Gravity',

    'ra': 'Right_Ascension_Deg',

    'dec': 'Declination_Deg',

    'sy_dist': 'Distance_From_Earth_Light_Years',

    'sy_gaiamag': 'Star_Gaia_Magnitude'

}

df.rename(columns=rename_dict, inplace=True)



# Generate and print Section 2.4 report grid table

print("="*80)

print("REPORT SECTION 2.4: CLEANING ACTIONS & RENAMING SUMMARY")

print("="*80)

print("| # | Action | Pandas Code Used | Result / Reason |")

print("|---|---|---|---|")

print(f"| 1 | Remove Duplicates | `df.drop_duplicates(inplace=True)` | Removed {duplicates_removed} duplicate rows (dataset is unique). |")

print("| 2 | Impute Numeric Columns (Stage 1) | `df[col] = df[col].fillna(df.groupby('discoverymethod')[col].transform('median'))` | Group-based median imputation using discovery method to preserve astronomical relationships. |")

print("| 3 | Impute Numeric Columns (Stage 2) | `df[col] = df[col].fillna(df[col].median())` | Global median fallback imputation applied to ensure zero remaining missing values. |")

print("| 4 | Fill Categorical Columns | `df[col] = df[col].fillna('Unknown')` | Missing categorical values in 'st_spectype' and 'st_metratio' filled with 'Unknown'. |")

print("| 5 | Type Casting | `df['disc_year'] = df['disc_year'].astype(int)` | Explicitly cast Discovery Year to integer for clean database styling and time-series plotting. |")

print("| 6 | Unit Conversion | `df['sy_dist'] = df['sy_dist'] * 3.26156` | Converted distance unit from Parsecs to Light Years (factor of 3.26156) for more intuitive public-facing visualization. |")

print("| 7 | Column Renaming | `df.rename(columns=rename_dict, inplace=True)` | Renamed all 29 fields to highly expressive, human-readable column headers for Power BI (e.g. Distance_From_Earth_Light_Years). |")

================================================================================
REPORT SECTION 2.4: CLEANING ACTIONS & RENAMING SUMMARY
================================================================================
| # | Action | Pandas Code Used | Result / Reason |
|---|---|---|---|
| 1 | Remove Duplicates | `df.drop_duplicates(inplace=True)` | Removed 0 duplicate rows (dataset is unique). |
| 2 | Impute Numeric Columns (Stage 1) | `df[col] = df[col].fillna(df.groupby('discoverymethod')[col].transform('median'))` | Group-based median imputation using discovery method to preserve astronomical relationships. |
| 3 | Impute Numeric Columns (Stage 2) | `df[col] = df[col].fillna(df[col].median())` | Global median fallback imputation applied to ensure zero remaining missing values. |
| 4 | Fill Categorical Columns | `df[col] = df[col].fillna('Unknown')` | Missing categorical values in 'st_spectype' and 'st_metratio' filled with 'Unknown'. |
| 5 | Type Casting | `df['disc_year'] = df['disc_year'].astype(int)` | Explicitly cast Discovery Year to integer for clean database styling and time-series plotting. |
| 6 | Unit Conversion | `df['sy_dist'] = df['sy_dist'] * 3.26156` | Converted distance unit from Parsecs to Light Years (factor of 3.26156) for more intuitive public-facing visualization. |
| 7 | Column Renaming | `df.rename(columns=rename_dict, inplace=True)` | Renamed all 29 fields to highly expressive, human-readable column headers for Power BI (e.g. Distance_From_Earth_Light_Years). |

## 5. REPORT SECTION 2.5: CLEANED DATASET FINAL STATE
Display data types and confirmation of 0 null values using `df.info()` (Cell D), show detailed summary statistics with `df.describe()` (Cell E), and export the final cleaned dataset to `cleaned_exoplanets.csv`.

In [7]:
# ==========================================

# Cell D: Run df.info() right after cleaning

# ==========================================

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6291 entries, 0 to 6290
Data columns (total 29 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Planet_Name                      6291 non-null   object
 1   Host_Star_Name                   6291 non-null   object
 2   Number_of_Stars                  6291 non-null   int64
 3   Number_of_Planets                6291 non-null   int64
 4   Number_of_Moons                  6291 non-null   int64
 5   Discovery_Method                 6291 non-null   object
 6   Discovery_Year                   6291 non-null   int64
 7   Discovery_Facility               6291 non-null   object
 8   Orbital_Period_Days              6291 non-null   float64
 9   Orbital_Distance_AU              6291 non-null   float64
 10  Planet_Radius_Earth_Units        6291 non-null   float64
 11  Planet_Radius_Jupiter_Units      6291 non-null   float64
 12  Planet_Mass_Earth_Units          6291 non-null   float64
 13  Planet_Mass_Jupiter_Units        6291 non-null   float64
 14  Mass_Measurement_Type            6291 non-null   object
 15  Orbit_Eccentricity               6291 non-null   float64
 16  Insolation_Flux_Earth_Units      6291 non-null   float64
 17  Equilibrium_Temperature_K        6291 non-null   float64
 18  Star_Spectral_Type               6291 non-null   object
 19  Star_Temperature_K               6291 non-null   float64
 20  Star_Radius_Solar_Units          6291 non-null   float64
 21  Star_Mass_Solar_Units            6291 non-null   float64
 22  Star_Metallicity                 6291 non-null   float64
 23  Star_Metallicity_Ratio           6291 non-null   object
 24  Star_Surface_Gravity             6291 non-null   float64
 25  Right_Ascension_Deg              6291 non-null   float64
 26  Declination_Deg                  6291 non-null   float64
 27  Distance_From_Earth_Light_Years  6291 non-null   float64
 28  Star_Gaia_Magnitude              6291 non-null   float64
dtypes: float64(18), int64(4), object(7)
memory usage: 1.4+ MB

In [8]:
# ==========================================

# Cell E: Run df.describe() to show summary statistics and export dataset

# ==========================================

summary_stats = df.describe()



# Export the processed dataframe to csv in current directory

df.to_csv('cleaned_exoplanets.csv', index=False)

print("Successfully exported the fully cleaned dataset to 'cleaned_exoplanets.csv'!")

summary_stats

Successfully exported the fully cleaned dataset to 'cleaned_exoplanets.csv'!

       Number_of_Stars  ...  Star_Gaia_Magnitude
count      6291.000000  ...          6291.000000
mean          1.101733  ...            12.323015
std           0.339946  ...             2.889906
min           1.000000  ...             2.364310
25%           1.000000  ...            10.599750
50%           1.000000  ...            13.138800
75%           1.000000  ...            14.589450
max           4.000000  ...            20.186100

[8 rows x 22 columns]